### ISSUE TITLE
Allow the creation of a useful 'friendly name'

### ISSUE THREAD

**Issue by deepcoder** [davidn/epa_uvindex#1]
Thank you for your work on this project!

I added two UV sensors. I end up with sensor.uv_index and sensor.uv_index_2. I am not allows to change the name as HA says:

```
This entity ('sensor.uv_index_2') does not have a unique ID, therefore its settings cannot be managed from the UI.
```
It would be helpful to give these sensor a 'sense' of they location.

Thx!

**Comment by davidn** [comment]
Thanks for the feedback! Let me know if this solves the issue for you.
