### ISSUE TITLE
UV Index always 6

### ISSUE THREAD

**Issue by kgstorm** [davidn/epa_uvindex#3]
Hello. 
I was mostly looking for a UV forecast, which I get from this. Thanks for the work.
But the UV Index has never changed.
For the past 24 hours (since adding the integration), the UV index has always been 6. 
It seems to be updating. The hourly numbers has changed from yesterday to today, but the UV Index is still 6.
Uv Index is supposed to be real time-ish, correct? Not the daily max, right?
Thanks
Kevin

**Comment by davidn** [comment]
The sensor value is the daily max, as that is how the other UV index integrations work (and how most UV index widgets around the internet work). The hourly UV index forecasts are stored as an attribute.

Your request makes sense though, so I might try and add a sensor for the current hourly UV index, but I don't have a ton of time for this project at the moment.

In the meantime, you can define a template sensor that pulls the current hourly UV index from the attribute and makes it it's own sensor that you could use.  I haven't tested it, but the template would be something like: 

```jinja
{% for forecast in state_attr("sensor.uv_index", "forecast") %}
  {% if forecast.datetime | as_local >= now() %}
    {{ forecast.uv_index }}
    {% break %}
  {% endif %}
{% endfor %}
```

**Comment by davidn** [comment]
This template seems to work pretty well, so I am going to add it to documentation as a solution rather than add a new sensor unecessarily
