### ISSUE TITLE
Unable to add integration under 2024.5.2

### ISSUE THREAD

**Issue by deepcoder** [davidn/epa_uvindex#5]
Followed your steps to install, however does not appear either under HACS 'downloaded' nor available to 'Add' as an Integration. If I try to re download it under HACS it says it is already there.

Thanks for your work and help!

**Comment by davidn** [comment]
Just to make sure I understand you correctly:

A) When you say "Followed your steps to install" do you mean you added it to HACS as a custom repository, following the "Recommended" set of instructions at https://github.com/davidn/epa_uvindex/blob/main/README.md?

B) When you say "does not appear either under HACS 'downloaded'" do you mean it does not appear on this page?
![Screenshot 2024-05-07 at 15-07-54 HACS – Home Assistant](https://github.com/davidn/epa_uvindex/assets/5889/2ca0a60e-b5ac-4f76-90b1-e262b2f65fcd)

C) When you say "nor available to 'Add' as an Integration" do you mean when you try to add the integration in the "Devices & Services" settings page that it doesn't appear:
![Screenshot from 2024-05-07 15-17-01](https://github.com/davidn/epa_uvindex/assets/5889/f9b5ec6c-ec15-454b-8809-923b10ca9736)

Thanks!

(BTW I don't have a working test set up at the moment, so I'm going to have to ask you to test things and won't be able to reproduce myself)

**Comment by deepcoder** [comment]
Q1: Yes, the steps I followed are the following from your Github readme.md, shown below.
Q2: searching for a number of combos for the name of your integration all failed to show any match.

FYI under the latest version of Home Assistant, the output from HACS is totally different. Not a good change IMHO. Picture below.

```
Navigate to the HACS add-on

Add https://github.com/davidn/epa_uvindex as a custom repository.

Go to the EPA UV Index integration and add it.

Restart Home Assistant

Go to Settings > Devices & Services, and on the Integration tab click "Add Integration". Select "EPA UV Index"

Enter the nearest city and state.

You will now have a sensor that provides the UV Index in that city.
```


<img width="1428" alt="hacs" src="https://github.com/davidn/epa_uvindex/assets/1409547/3939ebfc-9815-4c83-be9b-6a0603d0ad75">

**Comment by davidn** [comment]
Thanks for the speedy and complete response. that clarifies a lot.

I was able to get the new HACS view (by turning on "experimental features" in the configuration for the HACS integration), and have played with it a bit.

Adding the custom repository per step (2) of the instructions adds the integration to that HACS respository list but does not actually download the integration, so it might be there but filtered out by the "filtering by downloaded". Can you try disabling the filter by downloaded (ie press the CLEAR button in that screenshot) and see if "EPA UV Index" is listed? If so you then have to click on it and then on the details page for the integration click the download button.

If that works, I'll update the instructions. If it doesn't work, then I'll dig some more.

**Comment by deepcoder** [comment]
I'm not sure we are tracking on the same line. Let me know when you have a PRODUCTION 2024.5.x running and can test your integration, I'll give it a try then after you can test your own instruction.

1. I am not using 'experimental features' of HACS
2. As I indicated in my original post, when I try to redownload your custom integration, HACS tells me it is all ready download, see picture below.

Hope you can test you stuff, it seem like a useful addition to Home Assistant. Good hunting.


<img width="481" alt="hacs-download" src="https://github.com/davidn/epa_uvindex/assets/1409547/9eb38024-77d9-4478-a7fe-5e6ae8f98518">

**Comment by davidn** [comment]
Don't worry about the experiment thing. I just meant that I can now see the same thing as you:
![Screenshot 2024-05-08 at 09-24-56 HACS – Home Assistant](https://github.com/davidn/epa_uvindex/assets/5889/1c80b515-8131-4935-abcc-aafc558411c8)

I get the same error as you too.

But when I clear that filter I see the integration appears:
![Screenshot 2024-05-08 at 09-28-48 HACS – Home Assistant](https://github.com/davidn/epa_uvindex/assets/5889/b5583ff9-7fdd-4f1e-8c01-f425168efb20)

If you clear the filter do you see the EPA integration in the long list of integrations that are available?

**Comment by deepcoder** [comment]
Yes, that allows me to see your integration and I was able to add it.

Seems to be creating a sensor 'sensor.uv_index' successfully and delivering some values.

Thank you!

**Comment by davidn** [comment]
Great! I'm going to re-open this issue as a reminder to myself to update the documentation. I will give instructions for this alternative user interface and also will elaborate the "Go to the EPA UV Index integration and add it." step which is not very clear.
